### ISSUE TITLE
Recent changes in OGC API - Records conflict with this extension

### ISSUE THREAD

**Issue by m-mohr** [stac-extensions/language#2]
See https://github.com/opengeospatial/ogcapi-records/pull/211#issuecomment-1500323399
The default value of dir differs (and also the allowed values).

**Comment by yharby** [comment]
@m-mohr any new updates on that ?

**Comment by m-mohr** [comment]
Was reverted, read https://github.com/opengeospatial/ogcapi-records/pull/211#issuecomment-1500323399 + following comments for details
